### ISSUE TITLE
有什么能帮忙的？

### ISSUE THREAD

**Issue by kaixinbaba** [521xueweihan/hellogithub.com#11]
项目代码我大致看了遍，我工作是写java后端的，python也会一点，有什么能帮上忙的？有没有未来的规划？希望能出点力

**Comment by 521xueweihan** [comment]
加入前须知：https://github.com/HelloGitHub-Team/wiki

要做和在做的事情：https://github.com/521xueweihan/HelloGitHub/projects/1

**Comment by kaixinbaba** [comment]
![image](https://user-images.githubusercontent.com/22809336/86534474-47e5a800-bf0b-11ea-8775-ab9ea0d8f9c9.png)
我用的是pycharm，这些路径我这里是访问不到的，你们在IDE中有什么设置吗？ 我发现里面的导包路径有好几种写法
一种是上面图中以hellogithub为开头的路径
还有一种是以某一个子包下的py文件导入的
![image](https://user-images.githubusercontent.com/22809336/86534550-c7737700-bf0b-11ea-9e07-97bd3f7b1567.png)
你们是针对该项目有特别设置过PYTHONPATH吗？求助我需要怎么设置才能把这个项目跑起来

**Comment by 521xueweihan** [comment]
Python2 你再自己研究下吧。（部署运行算是加入面试题吧）
