### ISSUE TITLE
请问爬虫需要做什么呢？

### ISSUE THREAD

**Issue by notfresh** [521xueweihan/hellogithub.com#15]
TODO
已完成爬虫架子、GitHub spider，准备做view层、event信息流

我会一点爬虫，可以帮忙吗？
想知道爬虫的具体需求有什么

**Comment by 521xueweihan** [comment]
@notfresh 可以看看这里：https://mp.weixin.qq.com/s/9FUQ2i0HbemwfIj9sa1p0A
